# Python 기초 문법

### 목차

1. 숫자(int, float), 문자열(str)의 이해
2. numpy 라이브러리
3. pandas 라이브러리

### 목표 
1. int, str 등 객체 형식에 따라 적절한 메서드를 활용한다.
2. 여러 개의 값을 리스트 형식 등으로 저장하고 활용한다.
3. numpy와 pandas을 적절히 활용한다.


<br>
<hr>
<br>

## 1. 숫자, 문자열의 이해

### 1.1 숫자와 문자열

### 숫자 : int, float

In [1]:
1

1

In [2]:
# type()으로 데이터 타입 확인하기
type(1)

int

In [3]:
type(3.14)

float

In [4]:
# 숫자의 연산 (중간 공백은 상관 없음)
print(1 + 2*3/4)
print(1+2  * 3/  4)

2.5
2.5


In [5]:
# ** : 지수승
4**2

16

`print( )` : 출력  
`=` : 객체에 값 저장(할당)

### 문자 : str

In [6]:
## 큰따옴표, 작은따옴표 차이 없음
'삼성전자'

'삼성전자'

In [7]:
"삼성전자"

'삼성전자'

In [8]:
# 값의 할당(assign), 저장
a = '가나다'
b = '라마바'

a + b

'가나다라마바'

In [9]:
type('가')

str

In [10]:
# int : 정수형(3)
# float : 실수형(3.14)
# str : 문자열('아침')

#### [실습] x에 10.1을 저장하고, y에 101을 저장한 다음 더하기

In [1]:
x = 10.1
y = 101

x+y

111.1

<br>

### 1.2. 리스트(list) : 대표적인 파이썬의 데이터 바구니

### 1.2.1 리스트 생성

여러개의 값을 묶으면 한꺼번에 데이터를 관리하기 용이함.  
Python에서는 **리스트(list), 딕셔너리(dictionary), 튜플(tuple)** 형식 등으로 수열, 문자열을 다룸  

In [2]:
# 괄호의 종류
# [] : 대괄호     => 리스트, 인덱싱
# {} : 중괄호     => 딕셔너리
# () : (소)괄호   => 튜플

In [13]:
# 숫자 리스트
salary = [5000, 6000, 7000, 6000, 9000]
salary

[5000, 6000, 7000, 6000, 9000]

In [14]:
# 문자열 리스트
jobs = ['회로설계', '반도체공정설계', '신호 및 시스템 설계', 'S/W개발', '영업마케팅', '경영지원', '생산관리']
jobs

['회로설계', '반도체공정설계', '신호 및 시스템 설계', 'S/W개발', '영업마케팅', '경영지원', '생산관리']

In [15]:
# 리스트의 길이 확인
len(jobs)

7

#### [실습1] 1~10까지 숫자 중에서 마음대로 3개 숫자 선택해서 리스트로 만들어 저장하기



#### [실습2] 점심/저녁 메뉴 3개를 리스트로 묶어 menu로 저장하기 



In [3]:
list_num = [1, 5, 7]
list_num

[1, 5, 7]

In [5]:
menu = ['김치찌개', '볶음밥', '짜장면']
menu

['김치찌개', '볶음밥', '짜장면']

<br>

### 1.2.2 리스트의 주요 메서드

append( ) : 리스트에 값 추가 함수

In [18]:
# 더 이어 붙이기 
salary = [5000, 6000, 7000, 6000, 9000]
salary

[5000, 6000, 7000, 6000, 9000]

In [19]:
salary.append(10000)
salary

[5000, 6000, 7000, 6000, 9000, 10000]

In [20]:
# pop은 원하는 위치의 값을 삭제하는 함수
salary.pop(-1)
salary

[5000, 6000, 7000, 6000, 9000]

#### [실습] 관심있는 메뉴 3개를 묶은 menu에 append( )로 메뉴 "파스타" 하나 더 추가하기



In [6]:
menu.append('파스타')
menu

['김치찌개', '볶음밥', '짜장면', '파스타']

In [7]:
# 특정 위치 값 삭제하기 : pop 함수
menu.pop(-1)  # -1 : 마지막 위치
menu

['김치찌개', '볶음밥', '짜장면']

### 1.2.3. index의 활용   

만들어진 리스트에 대괄호 인덱스를 활용해서 원하는 위치의 값 선택

In [23]:
salary

[5000, 6000, 7000, 6000, 9000]

In [24]:
# 인덱싱 : 위치값으로 데이터 찾기(첫번째 위치값이 0)
salary[0] 

5000

In [25]:
## 콜론(:) -> 범위 지정(slicing)해서 데이터 찾기
salary[0:2]  # 0번째 위치부터 2번째 미만까지

[5000, 6000]

In [26]:
# salary[:2] # 처음부터 2번째 미만까지
# salary[2:] # 2번째부터 끝까지

In [27]:
# 인덱스를 활용한 값 업데이트
salary[0] = 8000
salary

[8000, 6000, 7000, 6000, 9000]

#### [실습] menu에서 첫번째 메뉴만 선택


#### [실습] menu에서 세번째 메뉴를 '우동'으로 변경



In [8]:
menu

['김치찌개', '볶음밥', '짜장면']

In [10]:
menu[2] = '우동'
menu

['김치찌개', '볶음밥', '우동']


<br>

#### 1.2.4. range( )를 활용한 수열 만들기

연속적인 수열을 만들 때는 `range( )` 활용


In [31]:
# 0부터 시작하는 range
range(10)

range(0, 10)

In [32]:
# range( )와 list( )를 활용한 숫자 리스트 생성
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
list(range(1, 20))
## 1부터 20미만까지

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [34]:
list(range(1, 19, 3))
## 1부터 19미만까지 3간격

[1, 4, 7, 10, 13, 16]

<br>

#### [실습] range( )와 list( )로 2013부터 2022까지 10개 연도 만들기




In [11]:
# range 함수는 범위 지정해서 수열을 만든다.
range(2013, 2023)

range(2013, 2023)

In [13]:
list(range(2013, 2023))

[2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]

### 1.3. for 반복문

In [37]:
# 1.1 숫자와 문자열
# 1.2 리스트(list)
# 1.3 for 반복문

In [38]:
# 간단한 for 예제
for i in [11, 12, 13]:
    print(i)

11
12
13


In [39]:
# 조금 복잡한 for문 예제

count = 0  # count라는 변수에 값 할당

for i in [11, 12, 13]:
    count += 1    # 반복할 때마다 count값을 1씩 증가시킨다 (count = count + 1)
    print(str(count) + '번째 값은 '+ str(i))

1번째 값은 11
2번째 값은 12
3번째 값은 13


In [40]:
# range는 for문에서 반복할 대상으로 많이 쓰인다.
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [41]:
for i in range(0, 10, 2):
    print(i)

0
2
4
6
8


<br>
<br>
<br>


## 2. numpy 라이브러리

**numpy** : 행렬 연산에 특화된 array 데이터 형식 지원

### 2.1. ndarray : n차원 array(배열)  => (2차원)행렬

In [42]:
import numpy as np

In [43]:
# 리스트 형식을 numpy array 형식으로 변환하기
x = [1, 2, 4, 8]

y = np.array(x)

In [44]:
y

array([1, 2, 4, 8])

In [45]:
type(y)

numpy.ndarray

In [46]:
# 수열 생성
## 0부터 10까지 101개 실수를 만들어보자.
np.linspace(0, 10, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [47]:
# 중첩(nested) 리스트를 활용한 다차원 행렬 만들기
y2 = np.array([ [1,2,3,4], [9,8,7,6] ])

print(y2.shape)  # 행렬 shape 확인 : 2x4 행렬
y2 

(2, 4)


array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [48]:
y3 = np.array([ [0, 1], [1, 0] ])

print(y3.shape)  # 행렬 shape 확인 : 2x2 행렬
y3

(2, 2)


array([[0, 1],
       [1, 0]])

<br>

### 2.2. ndarray와 연산 

numpy에는 ndarray에 적용할 수 있는 다양한 연산자와 함수가 준비되어 있음

In [49]:
y2  # 2x4 행렬

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [50]:
y3  # 2x2 행렬

array([[0, 1],
       [1, 0]])

In [51]:
# 산술 연산
y2*2 + 1

array([[ 3,  5,  7,  9],
       [19, 17, 15, 13]])

In [52]:
# 행렬 곱(내적)
y3@y2    # 2x2행렬 x 2x4행렬 => 2x4 행렬

array([[9, 8, 7, 6],
       [1, 2, 3, 4]])

In [53]:
import numpy as np
np.matmul(y3, y2)

array([[9, 8, 7, 6],
       [1, 2, 3, 4]])

In [54]:
# 행렬 요소 전체 합계
np.sum(y2)

40

In [55]:
# 행,열 옵션
# 열 : axis=0
# 행 : axis=1

In [56]:
# 열 합계
np.sum(y2, axis=0)

array([10, 10, 10, 10])

In [57]:
# 행 합계
np.sum(y2, axis=1)

array([10, 30])

In [58]:
# 행 평균
np.mean(y2, axis=1)

array([2.5, 7.5])

<br>

### 2.3. 부분 선택
대괄호 인덱스를 활용하여 ndarray에서 일부를 선택할 수 있습니다. 

In [59]:
# 1차원 array
y

array([1, 2, 4, 8])

In [60]:
# 특정 인덱스 선택 : 1번째 위치값은?
y[1]

2

In [61]:
# 슬라이스 활용
y[1:]

array([2, 4, 8])

In [62]:
y[:2]

array([1, 2])

In [63]:
y[-1]

8

In [64]:
y[:-1]

array([1, 2, 4])

In [65]:
# 2차원 array(행렬)
y2

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [66]:
# 다차원 행렬의 부분 선택 => 콤마 앞은 행, 뒤는 열
y2[:, :]

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [67]:
y2[0, 1:3]  # 0번째 행, 1~2번째 열

array([2, 3])

<br>

#### [실습] 행렬 생성 및 연산
1. 아래의 행렬을 만들고 *mat*으로 저장하기

$$\begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \\ 2 & 1 & 1 \end{bmatrix}$$

2. `np.max()`을 활용해서 *mat*에서 전체 최댓값 계산하기

3. `np.mean()`을 활용해서 *mat*에서 행 평균 계산하기

4. 첫번째부터 세번째 행의 두번째 열 선택


In [15]:
import numpy as np

# 1. 아래의 행렬을 만들고 mat으로 저장하기
mat = np.array( [  [1, 2, 1],
                   [3, 0, 1],
                   [0, 2, 4], 
                   [2, 1, 1] ] )
mat

array([[1, 2, 1],
       [3, 0, 1],
       [0, 2, 4],
       [2, 1, 1]])

In [16]:
# 2. np.max()을 활용해서 mat에서 전체 최댓값 계산하기
np.max(mat)

4

In [17]:
# 3. np.mean()을 활용해서 mat에서 행 평균 계산하기
np.mean(mat, axis=1)

array([1.33333333, 1.33333333, 2.        , 1.33333333])

In [18]:
# 4. 첫번째부터 세번째 행의 두번째 열 선택
mat[0:3, 1]

array([2, 0, 2])

<br>
<br>
<br>

## 3. pandas의 활용

**pandas** 라이브러리의 *read_csv()* 등의 함수를 활용해서 csv 등 데이터 불러오기 가능 

<br>

### 3.1. CSV 파일 불러오기



In [72]:
# pandas 라이브러리 불러오기
import pandas as pd

In [24]:
# pandas의 read_csv( ) 활용
df_ins= pd.read_csv("./data/insurance.csv")    # ./ : 현재 경로
df_ins= pd.read_csv("data/insurance.csv")      # 생략 가능
## "./data/insurance.csv" : 현재 경로에 있는 data 폴더 안에 있는 insurance.csv 파일

print(df_ins.shape)
df_ins.head()

(1338, 7)


age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [74]:
df_ins['age']   # 컬럼 한 개만 선택한다면 -> series(1차원)

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [75]:
# pandas가 가지는 두가지 데이터 형태

# series(행 or 열) : 1차원
# dataframe(행, 열) : 2차원

In [76]:
# 타입 확인
type(df_ins)  # dataframe 타입

pandas.core.frame.DataFrame

In [78]:
# 메서드(함수)의 확인(마침표 뒤에서 Tab 누르기)
df_ins.

In [79]:
# columns(변수 이름) 확인
df_ins.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [80]:
df_ins.head(1)

age     sex   bmi  children smoker     region    charges
0   19  female  27.9         0    yes  southwest  16884.924

<br>

#### [함께 실습] data 폴더의 PulseRates.csv를 불러와서 df_pr로 저장 후 
- 행,열 수 확인  
- 상위(head) 데이터 5개 확인

In [19]:
%pwd

'/Users/aiden/Dropbox/Mac/Desktop/code&data'

In [21]:
import pandas as pd
df_pr = pd.read_csv("data/PulseRates.csv")

In [22]:
print(df_pr.shape)
df_pr.head()

(110, 11)


Height  Weight  Age  Gender  Smokes  Alcohol  Exercise  Ran  Pulse1  \
0     173    57.0   18       2       2        1         2    2    86.0   
1     179    58.0   19       2       2        1         2    1    82.0   
2     167    62.0   18       2       2        1         1    1    96.0   
3     195    84.0   18       1       2        1         1    2    71.0   
4     173    64.0   18       2       2        1         3    2    90.0   

   Pulse2  Year  
0    88.0    93  
1   150.0    93  
2   176.0    93  
3    73.0    93  
4    88.0    93

<br>

### 3.2. 데이터프레임의 변수 선택 

- 변수 선택 : 대괄호 인덱스에 변수 이름 입력
- 리스트로 변수 이름을 묶고 여러 변수 한번에 선택 가능

In [25]:
# 한 변수 선택 
df_ins['age']  # Series 형식으로 출력됨

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [84]:
# 리스트를 활용한 복수 변수 선택
df_ins[['age','smoker','charges']]

age smoker      charges
0      19    yes  16884.92400
1      18     no   1725.55230
2      28     no   4449.46200
3      33     no  21984.47061
4      32     no   3866.85520
...   ...    ...          ...
1333   50     no  10600.54830
1334   18     no   2205.98080
1335   18     no   1629.83350
1336   21     no   2007.94500
1337   61    yes  29141.36030

[1338 rows x 3 columns]

<br>

### 3.3. 관측치 부분 선택

df[df_조건] : 데이터프레임 대괄호 인덱스에 조건을 넣어 원하는 데이터 선택 가능

In [85]:
# 변수 선택
df_ins['age']

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [86]:
# 조건 설정
df_ins['age'] < 30

0        True
1        True
2        True
3       False
4       False
        ...  
1333    False
1334     True
1335     True
1336     True
1337    False
Name: age, Length: 1338, dtype: bool

In [87]:
# 조건에 해당하는 데이터 추출 : df[df_조건]
df_ins[df_ins['age'] < 30]

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
10     25    male  26.220         0     no  northeast   2721.32080
12     23    male  34.400         0     no  southwest   1826.84300
...   ...     ...     ...       ...    ...        ...          ...
1328   23  female  24.225         2     no  northeast  22395.74424
1331   23  female  33.400         0     no  southwest  10795.93733
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500

[417 rows x 7 columns]

In [88]:
# 조건에 해당하는 데이터 추출 : df[df_조건]
df_ins_male = df_ins[ df_ins['sex'] == 'male' ] 
df_ins_male

age   sex     bmi  children smoker     region      charges
1      18  male  33.770         1     no  southeast   1725.55230
2      28  male  33.000         3     no  southeast   4449.46200
3      33  male  22.705         0     no  northwest  21984.47061
4      32  male  28.880         0     no  northwest   3866.85520
8      37  male  29.830         2     no  northeast   6406.41070
...   ...   ...     ...       ...    ...        ...          ...
1324   31  male  25.935         1     no  northwest   4239.89265
1325   61  male  33.535         0     no  northeast  13143.33665
1327   51  male  30.030         1     no  southeast   9377.90470
1329   52  male  38.600         2     no  southwest  10325.20600
1333   50  male  30.970         3     no  northwest  10600.54830

[676 rows x 7 columns]

<br>

#### [실습] 데이터 불러오기 및 부분 선택

1. `data`폴더에서 `StudentsPerformance.csv`를 불러와서 **df_sp**로 저장하기
2. **df_sp**에서 `math score`, `reading score`, `writing score` 세 변수 선택하기
3. **df_sp**에서 `math score`가 90이상인 데이터 선택하기
4. **df_sp**에서 `gender`가 *'female'*인 데이터 선택하기

In [26]:
# 1. data폴더에서 StudentsPerformance.csv를 불러와서 df_sp로 저장하기
df_sp = pd.read_csv('data/StudentsPerformance.csv')

In [28]:
# 2. df_sp에서 math score, reading score, writing score 세 변수 선택하기
df_sp[['math_score', 'reading_score', 'writing_score']]

math_score  reading_score  writing_score
0            72             72             74
1            69             90             88
2            90             95             93
3            47             57             44
4            76             78             75
..          ...            ...            ...
995          88             99             95
996          62             55             55
997          59             71             65
998          68             78             77
999          77             86             86

[1000 rows x 3 columns]

In [30]:
# 3. df_sp에서 math_score가 90이상인 데이터 선택하기

# df_sp에서 뭔가를 가져오고 싶다?
# => df_sp[조건]
df_sp[df_sp['math_score'] >= 90]

Unnamed: 0  gender race/ethnicity parental level of education  \
2             2  female        group B             master's degree   
34           34    male        group E                some college   
104         104    male        group C                some college   
114         114  female        group E           bachelor's degree   
121         121    male        group B          associate's degree   
149         149    male        group E          associate's degree   
165         165  female        group C           bachelor's degree   
171         171    male        group E            some high school   
179         179  female        group D            some high school   
233         233    male        group E            some high school   
263         263  female        group E                 high school   
286         286    male        group E          associate's degree   
299         299    male        group D          associate's degree   
306         306    male        group E                some college   
333         333    male        group B          associate's degree   
451         451  female        group E                some college   
458         458  female        group E           bachelor's degree   
469         469    male        group C                some college   
474         474  female        group B          associate's degree   
501         501  female        group B          associate's degree   
503         503  female        group E          associate's degree   
521         521  female        group C          associate's degree   
539         539    male        group A          associate's degree   
546         546  female        group A            some high school   
562         562    male        group C           bachelor's degree   
566         566  female        group E           bachelor's degree   
571         571    male        group A           bachelor's degree   
594         594  female        group C           bachelor's degree   
612         612    male        group C           bachelor's degree   
618         618    male        group D             master's degree   
623         623    male        group A                some college   
625         625    male        group D                some college   
659         659    male        group D          associate's degree   
685         685  female        group E             master's degree   
689         689    male        group E                some college   
710         710    male        group C                some college   
712         712  female        group D                some college   
717         717  female        group C          associate's degree   
719         719    male        group E          associate's degree   
736         736    male        group C          associate's degree   
779         779    male        group E          associate's degree   
784         784    male        group C           bachelor's degree   
808         808    male        group C                 high school   
815         815    male        group B            some high school   
845         845    male        group E             master's degree   
846         846    male        group C             master's degree   
855         855  female        group B           bachelor's degree   
864         864    male        group C          associate's degree   
873         873    male        group E          associate's degree   
886         886  female        group E          associate's degree   
903         903  female        group D           bachelor's degree   
916         916    male        group E           bachelor's degree   
919         919    male        group B                some college   
934         934    male        group C          associate's degree   
950         950    male        group E                 high school   
957         957  female        group D             master's degree   
962         962

#### End of script